ARG CRYSTAL_VERSION=1.0.0

# Build `digest_cli`
###############################################################################

FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine-build as build-digest

ARG CRYSTAL_VERSION=1.0.0
ARG PLACE_COMMIT="DEV"

WORKDIR /app

# Install the latest version of LibSSH2, ping, curl, git
RUN apk add --update --no-cache \
        bash \
        yaml-static

# Build a missing llvm artefact.
COPY scripts/build_llvm_ext.sh build_llvm_ext.sh
RUN ./build_llvm_ext.sh

COPY shard.lock .
COPY shard.yml .

RUN shards install --ignore-crystal-version

COPY src/digest_cli.cr src/digest_cli.cr

ENV CRYSTAL_VERSION=$CRYSTAL_VERSION

RUN CRYSTAL_PATH=lib:/usr/share/crystal/src/ \
    LLVM_CONFIG=$(/usr/share/crystal/src/llvm/ext/find-llvm-config) \
    PLACE_COMMIT=${PLACE_COMMIT} \
    UNAME_AT_COMPILE_TIME=true \
    shards build --static --error-trace --ignore-crystal-version digest_cli && \
    rm /usr/share/crystal/src/llvm/ext/llvm_ext.o

FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine

WORKDIR /app

ENV CRYSTAL_VERSION=$CRYSTAL_VERSION

# Install the latest version of LibSSH2, ping, curl, git
RUN apk add --update --no-cache \
        bash \
        ca-certificates \
        iputils \
        libssh2-static \
        yaml-static

RUN apk add --update --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

# Awaiting asdf patch for static compiler builds
#
# SHELL ["/bin/bash", "-l", "-c"]
#
# # Install asdf version manager
# RUN git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.8.0
# RUN $HOME/.asdf/bin/asdf plugin-add crystal https://github.com/asdf-community/asdf-crystal.git
#
# RUN echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc && \
#     echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.profile && \
#     source ~/.bashrc

RUN mkdir -p /app/bin/drivers

COPY shard.yml .
COPY shard.lock .
RUN shards install --ignore-crystal-version

COPY scripts /app/scripts

COPY --from=build-digest /app/bin/digest_cli /app/bin

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD /app/scripts/entrypoint-test.sh
