version: "3.7"

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-1.4.1}
    volumes:
      - ${PWD}/lib:/app/lib:rw
      - ${PWD}/coverage:/app/coverage
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
    environment:
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      SG_ENV: ${SG_ENV:-development}
      TZ: $TZ
