ARG CRYSTAL_VERSION=1.0.0
FROM crystallang/crystal:${CRYSTAL_VERSION}

ARG PLACE_COMMIT="DEV"

WORKDIR /app

RUN apt update
RUN apt install --no-install-recommends -y \
        bash \
        ca-certificates \
        curl \
        libssh2-1 libssh2-1-dev \
        llvm-10 llvm-10-dev \

# Install watchexec
RUN curl -sLO https://github.com/watchexec/watchexec/releases/download/cli-v1.16.0/watchexec-1.16.0-x86_64-unknown-linux-gnu.deb && \
    dpkg -i watchexec-1.16.0-x86_64-unknown-linux-gnu.deb && \
    rm -rf ./*.deb

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

# Install shards before adding source.
COPY shard.yml /app
COPY shard.lock /app
RUN shards install --ignore-crystal-version

# Build digest tool before copying rest of source for better caching.
RUN mkdir /app/src
COPY src/digest_cli.cr /app/src/digest_cli.cr

RUN CRYSTAL_PATH=lib:/usr/share/crystal/src/ \
    LLVM_CONFIG=$(/usr/share/crystal/src/llvm/ext/find-llvm-config) \
    shards build digest_cli --ignore-crystal-version --no-debug

COPY src/digest_cli.cr /app/src/digest_cli.cr

COPY scripts /app/scripts
COPY src /app/sr

RUN mkdir -p /app/bin/drivers

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Install asdf version manager
SHELL ["/bin/bash", "-l", "-c"]
RUN git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf --branch v0.8.0 && \
    $HOME/.asdf/bin/asdf plugin-add crystal https://github.com/asdf-community/asdf-crystal.git && \
    echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc && \
    echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.profile && \
    source ~/.bashrc

CMD /app/scripts/entrypoint-test.sh
