version: "3.7"

services:
  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
      args:
        crystal_version: ${CRYSTAL_VERSION:-1.0.0}
    volumes:
      - ./spec:/app/spec
      - ./src:/app/src
    environment:
      SG_ENV: ${SG_ENV:-development}
      TZ: $TZ
      GITHUB_ACTION: ${GITHUB_ACTION:-}