version: "3.7"

services:
  test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - ./spec:/app/spec
      - ./src:/app/src
    environment:
      ENV: ${ENV:-development}
      SG_ENV: ${SG_ENV:-development}
      TZ: $TZ
      GITHUB_ACTION: ${GITHUB_ACTION:-}
