name: CI
on:
  push:
jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        crystal:
          - nightly
          - 1.0.0
        multithreading: [false]
        include:
          - experimental: true
            multithreading: true
            crystal: nightly
          - experimental: true
            multithreading: false
            crystal: nightly
          - experimental: true
            multithreading: true
            crystal: 1.0.0

    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        if: ${{ !matrix.multithreading }}
        run: ./test
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
          TEST_LEGACY: "${{ matrix.experimental }}"
      - name: Test with multithreading
        if: ${{ matrix.multithreading }}
        run: ./test --multithreaded
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
          TEST_LEGACY: "${{ matrix.experimental }}"
