name: CI
on:
  push:
jobs:
  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false

  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main
