name: CI
on:
  push:
jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_legacy: [false, true]
        crystal:
          - latest
          - nightly
          - 1.0.0
    continue-on-error: ${{ matrix.test_legacy }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./test
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
          TEST_LEGACY: ${{ matrix.test_legacy }}
      - name: Test with multithreading
        run: ./test --multithreaded
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
          TEST_LEGACY: ${{ matrix.test_legacy }}
